title: Rejuvenation Walkthrough
description: A 100% guide for Rejuvenation by Lukatales!
theme: just-the-docs
color_scheme: dark
callouts:
  warning:
    title: Warning
    color: red

url: https://lukatales.github.io/rejuvwalkthrough/

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
