title: Rejuvenation Walkthrough
description: A starter template for a Jeykll site using the Just the Docs theme!
theme: just-the-docs
color_scheme: dark

url: https://lukatales.github.io/rejuvwalkthrough/

callouts:
  warning:
    title: Warning
    color: red

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
